// Errors
export const SONGS_ERROR = 'SONGS_ERROR';
export const FAVORITES_LIST_ERROR = 'FAVORITES_LIST_ERROR';

// SONGS
export const STORE_SONGS = 'STORE_SONGS';
export const STORE_FAVORITES = 'STORE_FAVORITES';
